[package]
name = "AoC2022_11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num-integer = "0.1"
primes = "0.3.0"
itertools = "0.10.5"